package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVoteResult<M extends BaseVoteResult<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setOpenid(java.lang.String openid) {
		set("openid", openid);
		return (M)this;
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public M setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
		return (M)this;
	}

	public java.lang.String getUnionid() {
		return get("unionid");
	}

	public M setVoteId(java.lang.Long voteId) {
		set("vote_id", voteId);
		return (M)this;
	}

	public java.lang.Long getVoteId() {
		return get("vote_id");
	}

	public M setVoteItemId(java.lang.Long voteItemId) {
		set("vote_item_id", voteItemId);
		return (M)this;
	}

	public java.lang.Long getVoteItemId() {
		return get("vote_item_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
