package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setAppName(java.lang.String appName) {
		set("app_name", appName);
		return (M)this;
	}

	public java.lang.String getAppName() {
		return get("app_name");
	}

	public M setAppid(java.lang.String appid) {
		set("appid", appid);
		return (M)this;
	}

	public java.lang.String getAppid() {
		return get("appid");
	}

	public M setSecret(java.lang.String secret) {
		set("secret", secret);
		return (M)this;
	}

	public java.lang.String getSecret() {
		return get("secret");
	}

	public M setAccessToken(java.lang.String accessToken) {
		set("access_token", accessToken);
		return (M)this;
	}

	public java.lang.String getAccessToken() {
		return get("access_token");
	}

	public M setExpireTime(java.util.Date expireTime) {
		set("expire_time", expireTime);
		return (M)this;
	}

	public java.util.Date getExpireTime() {
		return get("expire_time");
	}

}
