package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_config", "id", Config.class);
		arp.addMapping("t_vote", "id", Vote.class);
		arp.addMapping("t_vote_item", "id", VoteItem.class);
		arp.addMapping("t_vote_result", "id", VoteResult.class);
	}
}

