package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseVoteItem;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VoteItem extends BaseVoteItem<VoteItem> {
	public static final VoteItem dao = new VoteItem().dao();
	
	private Long Counts;
	
	public Long getCounts() {
		return Counts;
	}

	public void setCounts(Long counts) {
		Counts = counts;
	}

	public List<VoteItem> findVoteItemByVoteId(String voteId) {
		String sql = "select * from t_vote_item where vote_id=?";
		return dao.find(sql, voteId);
	}		
	public List<Record> getList(String voteId) {
		String sql = "select *,0 as counts from t_vote_item where vote_id=?";
		return Db.find(sql, voteId);
	}	
	
//	public List<VoteItem> getResultList(String voteId) {
//		String sql = "select * from t_vote_item vi, t_vote_result vr where vi.id=vr.vote_item_id vi.vote_id=?";
//		return dao.find(sql, voteId);
//	}	
	
}
