package com.demo.common.model;

import com.demo.common.model.base.BaseVote;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Vote extends BaseVote<Vote> {
	public static final Vote dao = new Vote().dao();
	
	public Page<Vote> getList(String openId, Integer pageNum, Integer pageSize) {
		String sql = "select * ";
		String fromSql = " from t_vote where openid=?";
		return dao.paginate(pageNum, pageSize, sql, fromSql, openId);
	}
	
}
