package com.demo.common.model;

import java.util.List;

import com.demo.common.model.base.BaseVoteResult;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VoteResult extends BaseVoteResult<VoteResult> {
	public static final VoteResult dao = new VoteResult().dao();
	
	public List<Record> getResults(String voteId) {
		String sql = "SELECT vote_item_id,COUNT(*) as cnt FROM t_vote_result WHERE vote_id=? GROUP BY vote_item_id";
		return Db.find(sql, voteId);
	}
	
	public List<VoteResult> findResultByVoteIdAndOepnId(Long voteId, String openId) {
		String sql = "SELECT * FROM t_vote_result WHERE vote_id=? and openid=?";
		return dao.find(sql, voteId, openId);
	}		
	
}
